CREATE TABLE "classes" (
    "Column_1" TEXT,
    "Column_2" INT
);
INSERT INTO "classes" VALUES
    ('Fluency in Information Technology',3),
    ('Mathematical Beauty in Rome',4),
    ('Mathematical Beauty in Rome Lab',6),
    ('Introduction to Programming I',5),
    ('Introduction to Programming with Matlab',7),
    ('Introduction to Computer Science: Java I',8),
    ('Introduction to Computer Science: Java II',8),
    ('Introduction to Computer Science and Object-Oriented Programming: Java',11),
    ('Basic Data Structures and Object-Oriented Design',12),
    ('Software Tools and Techniques Laboratory',15),
    ('Discrete Mathematics',20),
    ('Mathematics for Algorithms and Systems',21),
    ('Computer Organization and Systems Programming',30),
    ('Building and Programming Electronic Devices',42),
    ('UNIX Lab',80),
    ('C++ for Java Programmers',86),
    ('Freshman Seminar',87),
    ('Undergraduate Seminar',90),
    ('Perspectives in Computer Science and Engineering',91),
    ('Independent Study in Computer Science and Engineering',99),
    ('Advanced Data Structures',100),
    ('Design and Analysis of Algorithms',101),
    ('A Practical Introduction to Probability and Statistics',103),
    ('Theory of Computability',105),
    ('Introduction to Modern Cryptography',107),
    ('Software Engineering',110),
    ('Advanced Software Engineering',112),
    ('Ubiquitous Computing',118),
    ('Principles of Computer Operating Systems',120),
    ('Computer Networks',123),
    ('Networked Services',124),
    ('Software System Design and Implementation',125),
    ('Introduction to Computer Security',127),
    ('Programming Languages: Principles and Paradigms',130),
    ('Compiler Construction',131),
    ('Database System Principles',132),
    ('Database Systems Applications',132),
    ('Web Client Languages',134),
    ('Online Database Analytics Applications',135),
    ('Enterprise-Class Web Applications',136),
    ('Components and Design Techniques for Digital Systems',140),
    ('Digital Systems Laboratory',140),
    ('Introduction to Computer Architecture',141),
    ('Project in Computer Architecture',141),
    ('Microelectronic System Design',143),
    ('Embedded System Design Project',145),
    ('Advanced Processor Architecture Design Project',148),
    ('Introduction to Artificial Intelligence: Search and Reasoning',150),
    ('Introduction to Artificial Intelligence: Statistical Approaches',151),
    ('Introduction to Computer Vision',152),
    ('Cognitive Modeling',153),
    ('Recommender Systems and Web Mining',158),
    ('Introduction to Parallel Computing',160),
    ('Advanced Computer Graphics',163),
    ('GPU Programming',164),
    ('3D User Interaction',165),
    ('Image Processing',166),
    ('Computer Graphics',167),
    ('Computer Graphics II: Rendering',168),
    ('Computer Animation',169),
    ('Interaction Design',170),
    ('Maker Topics: Health Care Robotics',176),
    ('Biology Meets Computing',180),
    ('Molecular Sequence Analysis',181),
    ('Biological Databases',182),
    ('Computational Molecular Biology',184),
    ('Topics in Computer Science and Engineering',190),
    ('Seminar in CSE',191),
    ('Senior Seminar in Computer Science and Engineering',192),
    ('Teaching',195),
    ('CSE Honors Thesis Research for Undergraduates',199),
    ('Computability and Complexity',200),
    ('Advanced Complexity',201),
    ('Algorithm Design and Analysis',202),
    ('Advanced Algorithms',203),
    ('Logic in Computer Science',205),
    ('Lattice Algorithms and Applications',206),
    ('Modern Cryptography',207),
    ('Advanced Cryptography',208),
    ('Topics/Seminar in Algorithms, Complexity, and Logic',209),
    ('Topics/Seminar in Cryptography',209),
    ('Principles of Software Engineering',210),
    ('Software Testing and Analysis',211),
    ('Research Topics in Human-Computer Interaction',216),
    ('Advanced Topics in Software Engineering',218),
    ('Design at Large',219),
    ('Operating Systems',221),
    ('Computer Communication Networks',222),
    ('Internet Algorithmics',222),
    ('Distributed Computing and Systems',223),
    ('Graduate Networked Systems',224),
    ('Computer Security',227),
    ('Topics/Seminar in Computer Systems',229),
    ('Topics/Seminar in Computer Security',229),
    ('Principles of Programming Languages',230),
    ('Advanced Compiler Design',231),
    ('Principles of Database Systems',232),
    ('Database System Implementation',232),
    ('Database Theory',233),
    ('Introduction to Embedded Computing',237),
    ('Software for Embedded Systems',237),
    ('Validation and Testing of Embedded Systems',237),
    ('Design Automation and Prototyping for Embedded Systems',237),
    ('Topics/Seminar in Databases',239),
    ('Principles of Computer Architecture',240),
    ('Parallel Computer Architecture',240),
    ('Advanced Microarchitecture',240),
    ('VLSI Integration of Computing Circuitry',241),
    ('Introduction to Synthesis Methodologies in VLSI CAD',243),
    ('VLSI Test',244),
    ('Computer Aided Circuit Simulation and Verification',245),
    ('Algorithmic and Optimization Foundations for VLSI CAD',248),
    ('Topics/Seminar in Computer Architecture',249),
    ('Topics/Seminar in VLSI',249),
    ('Principles of Artificial Intelligence: Probabilistic Reasoning and Learning',250),
    ('Principles of Artificial Intelligence: Learning Algorithms',250),
    ('Machine Learning Theory',250),
    ('Computer Vision I',252),
    ('Computer Vision II',252),
    ('Selected Topics in Vision and Learning',252),
    ('Neural Networks for Pattern Recognition',253),
    ('Statistical Learning',254),
    ('Data Mining and Predictive Analytics',255),
    ('Recommender Systems and Web Mining',258),
    ('Cognitive Modeling',258),
    ('Seminar in Artificial Intelligence',259),
    ('Parallel Computation',260),
    ('System Support for Applications of Parallel Computation',262),
    ('Advanced Image Synthesis',272),
    ('Selected Topics in Graphics',274),
    ('Introduction to Robotics',276),
    ('Human Robot Interaction',276),
    ('Mathematics for Robotics',276),
    ('Healthcare Robotics',276),
    ('Algorithms in Computational Biology',280),
    ('Bioinformatics II: Sequence and Structure Analysis—Methods and Applications',282),
    ('Bioinformatics III: Functional Genomics',283),
    ('Personal Genomics for Bioinformaticians',284),
    ('Seminar in Computer Science and Engineering',290),
    ('Topics in Computer Science and Engineering',291),
    ('Faculty Research Seminar',292),
    ('Special Project in Computer Science and Engineering',293),
    ('Research Meeting in CSE',294),
    ('Independent Study',298),
    ('Research',299),
    ('Teaching Assistantship',500),
    ('Teaching Methods in Computer Science',599);
